# Generated by Django 3.1.5 on 2021-03-02 08:31

import chat.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_groupchat_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='code',
            field=models.CharField(default=chat.utils.generate_unique_code, max_length=8, unique=True),
        ),
    ]
