# Generated by Django 3.1.5 on 2021-03-04 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_groupnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupnotification',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
